import { Routes } from '@angular/router';
import { authGuard, roleGuard } from './core/guards/auth.guard';
import { UserRole } from './core/models';
export const routes: Routes = [
  { path: '', loadComponent: () => import('./features/home/home.component').then(m => m.HomeComponent) },
  { path: 'login', loadComponent: () => import('./features/auth/login/login.component').then(m => m.LoginComponent) },
  { path: 'register', loadComponent: () => import('./features/auth/register/register.component').then(m => m.RegisterComponent) },
  { path: 'products', loadComponent: () => import('./features/products/product-list/product-list.component').then(m => m.ProductListComponent) },
  { path: 'products/:id', loadComponent: () => import('./features/products/product-detail/product-detail.component').then(m => m.ProductDetailComponent) },
  { path: 'quote', loadComponent: () => import('./features/quote/quote.component').then(m => m.QuoteComponent) },
  { path: 'about', loadComponent: () => import('./features/about/about.component').then(m => m.AboutComponent) },
  { path: 'contact', loadComponent: () => import('./features/contact/contact.component').then(m => m.ContactComponent) },
  { path: 'policies', canActivate:[authGuard], loadComponent: () => import('./features/policy/policy-list/policy-list.component').then(m => m.PolicyListComponent) },
  { path: 'policies/endorsement', canActivate:[authGuard], loadComponent: () => import('./features/policy/endorsement/endorsement.component').then(m => m.EndorsementComponent) },
  { path: 'policies/renewal', canActivate:[authGuard], loadComponent: () => import('./features/policy/renewal/renewal.component').then(m => m.RenewalComponent) },
  { path: 'policies/:id', canActivate:[authGuard], loadComponent: () => import('./features/policy/policy-detail/policy-detail.component').then(m => m.PolicyDetailComponent) },
  { path: 'claims', canActivate:[authGuard], loadComponent: () => import('./features/claims/claim-list/claim-list.component').then(m => m.ClaimListComponent) },
  { path: 'claims/submit', canActivate:[authGuard], loadComponent: () => import('./features/claims/claim-submit/claim-submit.component').then(m => m.ClaimSubmitComponent) },
  { path: 'claims/:id', canActivate:[authGuard], loadComponent: () => import('./features/claims/claim-detail/claim-detail.component').then(m => m.ClaimDetailComponent) },
  { path: 'payment', canActivate:[authGuard], loadComponent: () => import('./features/payment/payment-history/payment-history.component').then(m => m.PaymentHistoryComponent) },
  { path: 'payment/schedule', canActivate:[authGuard], loadComponent: () => import('./features/payment/schedule/payment-schedule.component').then(m => m.PaymentScheduleComponent) },
  { path: 'customer/profile', canActivate:[authGuard], loadComponent: () => import('./features/customer/profile/profile.component').then(m => m.ProfileComponent) },
  { path: 'customer/360', canActivate:[authGuard], loadComponent: () => import('./features/customer/customer-360/customer-360.component').then(m => m.Customer360Component) },
  { path: 'notifications', canActivate:[authGuard], loadComponent: () => import('./features/notifications/notifications.component').then(m => m.NotificationsComponent) },
  { path: 'agent', canActivate:[authGuard], loadComponent: () => import('./features/agent/dashboard/agent-dashboard.component').then(m => m.AgentDashboardComponent) },
  { path: 'agent/clients', canActivate:[authGuard], loadComponent: () => import('./features/agent/clients/agent-clients.component').then(m => m.AgentClientsComponent) },
  { path: 'agent/leads', canActivate:[authGuard], loadComponent: () => import('./features/agent/leads/agent-leads.component').then(m => m.AgentLeadsComponent) },
  { path: 'agent/commission', canActivate:[authGuard], loadComponent: () => import('./features/agent/commission/agent-commission.component').then(m => m.AgentCommissionComponent) },
  { path: 'agent/leaderboard', canActivate:[authGuard], loadComponent: () => import('./features/agent/leaderboard/agent-leaderboard.component').then(m => m.AgentLeaderboardComponent) },
  { path: 'underwriting', canActivate:[authGuard], loadComponent: () => import('./features/underwriting/underwriting.component').then(m => m.UnderwritingComponent) },
  { path: 'claims-handler', canActivate:[authGuard], loadComponent: () => import('./features/claims-handler/claims-handler.component').then(m => m.ClaimsHandlerComponent) },
  { path: 'partner', canActivate:[authGuard], loadComponent: () => import('./features/partner/dashboard/partner-dashboard.component').then(m => m.PartnerDashboardComponent) },
  { path: 'partner/direct-billing', canActivate:[authGuard], loadComponent: () => import('./features/partner/direct-billing/direct-billing.component').then(m => m.DirectBillingComponent) },
  { path: 'admin', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/dashboard/admin-dashboard.component').then(m => m.AdminDashboardComponent) },
  { path: 'admin/users', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/user-management/user-management.component').then(m => m.UsermanagementComponent) },
  { path: 'admin/products', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/product-management/product-management.component').then(m => m.ProductmanagementComponent) },
  { path: 'admin/policies', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/policy-management/policy-management.component').then(m => m.PolicymanagementComponent) },
  { path: 'admin/claims', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/claims-management/claims-management.component').then(m => m.ClaimsmanagementComponent) },
  { path: 'admin/agents', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/agent-management/agent-management.component').then(m => m.AgentmanagementComponent) },
  { path: 'admin/partners', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/partner-management/partner-management.component').then(m => m.PartnermanagementComponent) },
  { path: 'admin/reports', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/reports/admin-reports.component').then(m => m.AdminreportsComponent) },
  { path: 'admin/audit', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/audit-log/audit-log.component').then(m => m.AuditlogComponent) },
  { path: 'admin/config', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/system-config/system-config.component').then(m => m.SystemconfigComponent) },
  { path: 'admin/monitoring', canActivate:[roleGuard], data:{roles:[UserRole.ADMIN,UserRole.SUPER_ADMIN]}, loadComponent: () => import('./features/admin/monitoring/monitoring.component').then(m => m.MonitoringComponent) },
  { path: '**', redirectTo: '' }
];
